import { ProductType, Unit } from '~/enums';
import { Product } from '~/types';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Pomidor',
    type: ProductType.global,
    units: [Unit.grams, Unit.pieces],
  },
  {
    id: 2,
    name: 'Masło',
    type: ProductType.global,
    units: [Unit.pieces, Unit.grams],
  },
  { id: 3, name: 'Chleb', type: ProductType.global, units: [Unit.pieces] },
  {
    id: 4,
    name: 'Parówki',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.packs],
  },
  {
    id: 5,
    name: 'Woda',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 6,
    name: 'Kinder Bueno',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 41,
    name: 'Pomidor',
    type: ProductType.global,
    units: [Unit.grams, Unit.pieces],
  },
  {
    id: 42,
    name: 'Masło',
    type: ProductType.global,
    units: [Unit.pieces, Unit.grams],
  },
  { id: 43, name: 'Chleb', type: ProductType.global, units: [Unit.pieces] },
  {
    id: 44,
    name: 'Parówki',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.packs],
  },
  {
    id: 45,
    name: 'Woda',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 46,
    name: 'Kinder Bueno',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 31,
    name: 'Pomidor',
    type: ProductType.global,
    units: [Unit.grams, Unit.pieces],
  },
  {
    id: 32,
    name: 'Masło',
    type: ProductType.global,
    units: [Unit.pieces, Unit.grams],
  },
  { id: 33, name: 'Chleb', type: ProductType.global, units: [Unit.pieces] },
  {
    id: 34,
    name: 'Parówki',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.packs],
  },
  {
    id: 35,
    name: 'Woda',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 36,
    name: 'Kinder Bueno',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 11,
    name: 'Pomidor',
    type: ProductType.global,
    units: [Unit.grams, Unit.pieces],
  },
  {
    id: 12,
    name: 'Masło',
    type: ProductType.global,
    units: [Unit.pieces, Unit.grams],
  },
  { id: 13, name: 'Chleb', type: ProductType.global, units: [Unit.pieces] },
  {
    id: 14,
    name: 'Parówki',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.packs],
  },
  {
    id: 15,
    name: 'Woda',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 16,
    name: 'Kinder Bueno',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 21,
    name: 'Pomidor',
    type: ProductType.global,
    units: [Unit.grams, Unit.pieces],
  },
  {
    id: 22,
    name: 'Masło',
    type: ProductType.global,
    units: [Unit.pieces, Unit.grams],
  },
  { id: 23, name: 'Chleb', type: ProductType.global, units: [Unit.pieces] },
  {
    id: 24,
    name: 'Parówki',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.packs],
  },
  {
    id: 25,
    name: 'Woda',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
  {
    id: 26,
    name: 'Kinder Bueno',
    type: ProductType.local,
    sectionId: 1,
    units: [Unit.milliliters, Unit.pieces, Unit.pieces],
  },
];
